# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::RSpec; end
module Yast::WFM::Label; end
module Yast::WFM::Mode; end
module Yast::WFM::Popup; end
module Yast::WFM::Report; end
